package iuh.fit.se.enums;

public enum LoaiNguyenLieu {
    NGUYEN_LIEU_THO,       // Sữa tươi, trà lá, bột matcha thô, trân châu sống...
    BAN_THANH_PHAM,        // Cốt trà sữa, trân châu đã luộc, thạch pudding đã nấu...
    TOPPING_AN_LIEN        // Thạch dừa đóng hộp, trân châu trắng đóng túi...
}
